"""Add stripe_price_id to SlidingScaleOption

Revision ID: 6e7d89532235
Revises: 3fb194cc1ca6
Create Date: 2025-06-27 15:35:34.590154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e7d89532235'
down_revision = '3fb194cc1ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sliding_scale_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_price_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sliding_scale_options', schema=None) as batch_op:
        batch_op.drop_column('stripe_price_id')

    # ### end Alembic commands ###
